bases:
- ../../giantswarm/additional-resources
- ../../giantswarm/additional-rest-api-resources
helmCharts:
  - name: flux-app
    includeCRDs: false
    namespace: flux-giantswarm
    repo: https://giantswarm.github.io/giantswarm-catalog/
    releaseName: flux-giantswarm
    version: v0.11.0
    valuesInline:
      crds:
        install: true
      images:
        registry: docker.io
patches:
- target:
    kind: ClusterRole
    name: crd-controller
  patch: |-
    - op: replace
      path: /metadata/name
      value: crd-controller-giantswarm
    - op: replace
      path: /rules/10/resourceNames/0
      value: flux-app-pvc-psp-giantswarm
- target:
    kind: PodSecurityPolicy
    name: flux-app-pvc-psp
  patch: |-
    - op: replace
      path: /metadata/name
      value: flux-app-pvc-psp-giantswarm
- target:
    kind: ClusterRoleBinding
    name: cluster-reconciler
  patch: |-
    - op: replace
      path: /metadata/name
      value: cluster-reconciler-giantswarm
- target:
    kind: ClusterRoleBinding
    name: crd-controller
  patch: |-
    - op: replace
      path: /metadata/name
      value: crd-controller-giantswarm
    - op: replace
      path: /roleRef/name
      value: crd-controller-giantswarm
- target:
    kind: CustomResourceDefinition
    name: ".*"
  patch: |-
    - op: add
      # https://github.com/kubernetes-sigs/kustomize/issues/1256
      path: /metadata/annotations/kustomize.toolkit.fluxcd.io~1prune
      value: disabled
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-automation-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: notification-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags-notification.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
      namespace: flux-giantswarm
    path: ../../giantswarm/patches/flags-source.yaml
patchesStrategicMerge:
- ../../giantswarm/patches/flux-app-pvc-psp.yaml
- ../../giantswarm/patches/kustomize-controller.yaml
resources:
- customer-flux-kustomization.yaml
- flux-kustomization.yaml
- gitrepository-collection.yaml
