---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # See: https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing
  application.instanceLabelKey: |
    argocd.argoproj.io/instance
  configManagementPlugins: |
    # this will be updated after we have working configctl plugin ready
    - name: myPlugin
      init:                          # Optional command to initialize application source directory
        command: ["ls"]
        args: ["."]
      generate:                      # Command to generate manifests YAML
        command: ["sh"]
        args: ["-c", "echo '################ ERROR #######' >&2 ; exit 5"]
  repository.credentials: |
    - url: https://github.com/giantswarm
      usernameSecret:
        name: github-giantswarm-https-credentials
        key: username
      passwordSecret:
        name: github-giantswarm-https-credentials
        key: password
