---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management-clusters-fleet-collections
  namespace: argocd
spec:
  description: Management Clusters Fleet Collections
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
  destinations:
    - namespace: giantswarm
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-clusters-fleet-collections
  namespace: argocd
spec:
  project: management-clusters-fleet-collections
  source:
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: giantswarm
  syncPolicy:
    automated:
      prune: true 
      allowEmpty: true

