---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: collections
  namespace: argocd
spec:
  namespaceResourceBlacklist:
  - group: 'application.giantswarm.io'
    kind: Chart
  description: Management Clusters Fleet Collection
  sourceRepos:
    - '*'
  destinations:
    - namespace: giantswarm
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-collection
  namespace: argocd
spec:
  project: collections
  source:
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: giantswarm
  syncPolicy:
    automated:
      prune: true 
      allowEmpty: true
      selfHeal: true
