---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management-clusters-fleet
  namespace: argocd
spec:
  description: Management Clusters Fleet
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/giantswarm/management-clusters-fleet.git'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-clusters-fleet-argocd
  namespace: argocd
spec:
  project: management-clusters-fleet
  source:
    repoURL: https://github.com/giantswarm/management-clusters-fleet.git
    targetRevision: main
    path: build/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-clusters-fleet
  namespace: argocd
spec:
  project: management-clusters-fleet
  source:
    repoURL: https://github.com/giantswarm/management-clusters-fleet.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
      allowEmpty: true 
