---
apiVersion: v1
kind: Secret
metadata:
  name: repository-giantswarm-openstack-app-collection
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/giantswarm/openstack-app-collection
