---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    path: manifests/provider/gcp
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: collections
  namespace: argocd
spec:
  description: Management Cluster gcp Collection
  sourceRepos:
    - 'https://github.com/giantswarm/config.git'
    - 'https://github.com/giantswarm/gcp-app-collection.git'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-collection
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/giantswarm/gcp-app-collection.git
    path: manifests
