---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 30s
  path: ./manifests/provider/aws-flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: flux-system

