bases:
- ../../customer/additional-resources
helmCharts:
  - name: flux-app
    includeCRDs: false
    namespace: flux-system
    repo: https://giantswarm.github.io/giantswarm-catalog/
    releaseName: customer-flux
    version: v0.11.0
    valuesInline:
      crds:
        install: false
      images:
        registry: docker.io
patches:
- target:
    kind: ClusterRoleBinding
    name: crd-controller
  patch: |-
    - op: replace
      path: /kind
      value: RoleBinding
    - op: add
      path: /metadata/namespace
      value: flux-system
- target:
    kind: ClusterRoleBinding
    name: cluster-reconciler
  patch: |-
    - op: replace
      path: /kind
      value: RoleBinding
    - op: add
      path: /metadata/namespace
      value: flux-system
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    path: ../../customer/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-automation-controller
      namespace: flux-system
    path: ../../customer/patches/flags-image-automation.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
    path: ../../customer/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    path: ../../customer/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: notification-controller
      namespace: flux-system
    path: ../../customer/patches/flags-notification.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    path: ../../customer/patches/flags-source.yaml
resources: []
