apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: giantswarm-flux
spec:
  template:
    spec:
      hostAliases:
        - ip: "192.168.190.100"
          hostnames:
          - "github.com"
