---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: giantswarm-flux
spec:
  interval: 30s
  path: ./bootstrap/gs-azure
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: giantswarm-flux
