---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: giantswarm-apiextensions-azure
  namespace: flux-giantswarm
spec:
  interval: 30s
  path: ./helm/crds-azure/templates
  prune: false
  sourceRef:
    kind: GitRepository
    name: giantswarm-apiextensions
    namespace: flux-giantswarm
