---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/giantswarm/config
    - url: https://github.com/giantswarm/vmware-app-collection
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    path: manifests/provider/vmware
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: collections
  namespace: argocd
spec:
  description: Management Cluster VMWare collection
  sourceRepos:
    - 'https://github.com/giantswarm/vmware-app-collection.git'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-collection
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/giantswarm/vmware-app-collection.git
    path: helm/vmware-app-collection-chart/templates
