apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rest-api-collection
  namespace: flux-giantswarm
spec:
  interval: 10s
  path: ./flux-manifests
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: rest-api-collection
    namespace: flux-giantswarm
  targetNamespace: giantswarm
