---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # See: https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing
  application.instanceLabelKey: "argocd.argoproj.io/instance"
  configManagementPlugins: |
    - name: konfigure
      generate:
        command: ["sh"]
        args:
        - "-c"
        - "konfigure generate
          --installation=${KONFIGURE_INSTALLATION}
          --app-name=${KONFIGURE_APP_NAME}
          --app-catalog=${KONFIGURE_APP_CATALOG}
          --app-version=${KONFIGURE_APP_VERSION}
          --name=${ARGOCD_APP_NAME}
          --namespace=${ARGOCD_APP_NAMESPACE}
          --vault-secret-name=argocd-vault-token
          --vault-secret-namespace=argocd"
  repository.credentials: |
    - url: https://github.com/giantswarm
      usernameSecret:
        name: github-giantswarm-https-credentials
        key: username
      passwordSecret:
        name: github-giantswarm-https-credentials
        key: password

