---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # See: https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing
  application.instanceLabelKey: "argocd.argoproj.io/instance"
  configManagementPlugins: |
    - name: konfigure
      generate:
        command: ["sh"]
        args:
        - "-c"
        - "konfigure generate
          --installation=${KONFIGURE_INSTALLATION}
          --app-name=${KONFIGURE_APP_NAME}
          --app-destination-namespace=${ARGOCD_APP_NAMESPACE}
          --app-catalog=${KONFIGURE_APP_CATALOG}
          --app-version=${KONFIGURE_APP_VERSION}
          --name=${ARGOCD_APP_NAME}"
  # Helm status: https://github.com/helm/helm/blob/main/pkg/release/status.go
  # ArgoCD status: https://github.com/argoproj/gitops-engine/blob/master/pkg/health/health.go
  resource.customizations.health.application.giantswarm.io_App: |
    hs = {}
    hs.status = "Progressing"
    hs.message = "Waiting for Chart to be installed"
    if obj.status ~= nil then
      if obj.status.release ~= nil then
        if obj.status.release.status == "already-exists" then
          hs.status = "Degraded"
        elseif obj.status.release.status == "deployed" then
          hs.status = "Healthy"
        elseif obj.status.release.status == "failed" then
          hs.status = "Degraded"
        elseif obj.status.release.status == "pending-install" then
          hs.status = "Progressing"
        elseif obj.status.release.status == "pending-rollback" then
          hs.status = "Progressing"
        elseif obj.status.release.status == "pending-upgrade" then
          hs.status = "Progressing"
        elseif obj.status.release.status == "superseded" then
          hs.status = "Suspended"
        elseif obj.status.release.status == "uninstalled" then
          hs.status = "Degraded"
        elseif obj.status.release.status == "uninstalling" then
          hs.status = "Progressing"
        else
          hs.status = "Unknown"
        end
        hs.message = obj.status.release.reason
      end
    end
    return hs
