$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dex-server
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-dex-server
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-dex-server
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: argocd-dex-server
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
