---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: Management Clusters Fleet Argo CD
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/giantswarm/management-clusters-fleet.git'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: flux-system
      server: https://kubernetes.default.svc
    - namespace: giantswarm
      server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
    - group: 'application.giantswarm.io'
      kind: Chart
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/giantswarm/management-clusters-fleet.git
    targetRevision: prep-flux
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
