apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: flux

resources:
  - namespace.yaml
  - configmap.yaml
  - app.yaml
  - kyverno_cluster_policy.yaml
