---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-giantswarm
spec:
  interval: 30s
  path: ./bootstrap/gs-openstack-gravity
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: flux-giantswarm
