- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - --events-addr=http://notification-controller/
    - --watch-all-namespaces
    - --log-level=trace
    - --log-encoding=json
    - --enable-leader-election
