---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-testing
  namespace: flux-giantswarm
spec:
  interval: 30s
  path: ./bootstrap/gs-aws-testing
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: flux-giantswarm
