apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-namespace-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
