---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-test-mc-only
  namespace: flux-giantswarm
spec:
  force: true
  interval: 30s
  path: ./bootstrap/gs-testing
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: flux-giantswarm
