- op: replace
  path: /spec/template/spec/containers/0/args/1
  value: "--watch-all-namespaces=false"
- op: replace
  path: /spec/template/spec/containers/0/args/6
  value: "--storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.$(CLUSTER_DOMAIN)"
- op: add
  path: /spec/template/spec/containers/0/env/1
  value:
    name: CLUSTER_DOMAIN
    valueFrom:
      configMapKeyRef:
        key: CLUSTER_DOMAIN
        name: management-cluster-metadata
        optional: false
