apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      hostAliases:
      - $patch: replace
        ip: "192.168.190.100"
        hostnames:
        - "github.com"
