---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: remove-full-cluster-domain-name
  url: https://github.com/giantswarm/management-clusters-fleet
