---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: giantswarm-config
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: feature/update-flux
  url: https://github.com/giantswarm/config
  secretRef:
    name: github-giantswarm-https-credentials
