---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: gs-eric-vcd_auto_branch
  url: https://github.com/giantswarm/management-clusters-fleet
