---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: giantswarm-apiextensions
  namespace: flux-giantswarm
spec:
  interval: 5m
  ref:
    branch: master
  url: https://github.com/giantswarm/apiextensions
  secretRef:
    name: github-giantswarm-https-credentials

