---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: capi-collection
  url: https://github.com/giantswarm/management-clusters-fleet
