apiVersion: batch/v1
kind: Job
metadata:
  generateName: flux-remove-crd-labels
  namespace: flux-giantswarm
  labels:
    app.kubernetes.io/name: flux-giantswarm
    app.kubernetes.io/component: remove-crd-labels
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux-giantswarm
        app.kubernetes.io/component: remove-crd-labels
    spec:
      serviceAccountName: automation
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      containers:
      - name: kubectl
        image: giantswarm/docker-kubectl:1.23.6
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset
          for crd in $(kubectl get crd | grep fluxcd | awk '{ print $1 }')
          do
            kubectl label crd $crd kustomize.toolkit.fluxcd.io/name-
            kubectl label crd $crd kustomize.toolkit.fluxcd.io/namespace-
          done
        securityContext:
          readOnlyRootFilesystem: true
      restartPolicy: Never
  backoffLimit: 4
