apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  interval: 10s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: collection
    namespace: flux-giantswarm
  targetNamespace: giantswarm
