apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: giantswarm-apiextensions-common
  namespace: flux-giantswarm
spec:
  interval: 30s
  path: ./helm/crds-common/templates
  prune: false
  sourceRef:
    kind: GitRepository
    name: giantswarm-apiextensions
    namespace: flux-giantswarm
  # none of the apiextensions-application CRDs, please
  patches:
    - target:
        kind: CustomResourceDefinition
        name: appcatalogentries.application.giantswarm.io
      patch: |-
        $patch: delete
    - target:
        kind: CustomResourceDefinition
        name: appcatalogs.application.giantswarm.io
      patch: |-
        $patch: delete
    - target:
        kind: CustomResourceDefinition
        name: apps.application.giantswarm.io
      patch: |-
        $patch: delete
    - target:
        kind: CustomResourceDefinition
        name: catalogs.application.giantswarm.io
      patch: |-
        $patch: delete
    - target:
        kind: CustomResourceDefinition
        name: charts.application.giantswarm.io
      patch: |-
        $patch: delete
