---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resume-collection-kustomization
  namespace: flux-giantswarm
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - resume
                - kustomization
                - collection
                - --namespace
                - flux-giantswarm
              image: docker.io/fluxcd/flux-cli:v0.27.0
              name: resume-collection-kustomization
          serviceAccountName: automation
          restartPolicy: OnFailure
