namespace: "giantswarm-flux"
bases:
- ../../giantswarm/additional-resources
helmCharts:
  - name: flux-app
    includeCRDs: true
    namespace: giantswarm-flux
    repo: https://giantswarm.github.io/giantswarm-catalog/
    releaseName: giantswarm-flux
    version: v0.7.1
    valuesInline:
      crds:
        install: true
      images:
        registry: docker.io
patchesStrategicMerge:
- ../../giantswarm/patches/flux-app-pvc-psp.yaml
- ../../giantswarm/patches/kustomize-controller.yaml
resources:
- flux-kustomization.yaml
