namespace: "giantswarm-flux"
bases:
- ../../giantswarm/additional-resources
helmCharts:
  - name: flux-app
    includeCRDs: true
    namespace: giantswarm-flux
    repo: https://giantswarm.github.io/giantswarm-catalog/
    releaseName: giantswarm-flux
    version: v0.7.1
    valuesInline:
      crds:
        install: true
      images:
        registry: docker.io
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-automation-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-reflector-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: notification-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags-notification.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
      namespace: giantswarm-flux
    path: ../../giantswarm/patches/flags.yaml
patchesStrategicMerge:
- ../../giantswarm/patches/flux-app-pvc-psp.yaml
- ../../giantswarm/patches/kustomize-controller.yaml
resources:
- flux-kustomization.yaml
