name: Validate bootstrap
on: push
jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: YAMLLint
        uses: docker://quay.io/giantswarm/yamllint:1.26
        with:
          args: bootstrap/
